#!/bin/bash
configPath="/var/www/html/cfg/config.ini"
USER=""
PASSWORD=""
inbox=`grep 'inbox[ ]*=[ ]*' $configPath`
userName=`grep 'user[ ]*=[ ]*' $configPath`
FTPHost=`grep 'FTPHost[ ]*=[ ]*' $configPath`
FTPPath=`grep 'FTPPath[ ]*=[ ]*' $configPath`

userName=${userName//[[:blank:]]/}
inbox=${inbox//[[:blank:]]/}
FTPHost=${FTPHost//[[:blank:]]/}
FTPPath=${FTPPath//[[:blank:]]/}

inbox=${inbox//\"/}
FTPHost=${FTPHost//\"/}
FTPPath=${FTPPath//\"/}
IFSBak=$IFS
IFS="="

tokens=( $userName )
userName=${tokens[1]}

tokens=( $inbox )
inbox=${tokens[1]}

tokens=( $FTPHost )
FTPHost=${tokens[1]}

tokens=( $FTPPath )
FTPPath=${tokens[1]}
IFS=$IFSBak

if [ ! -d "$inbox/$userName/tmp"  ]; then
    mkdir -p $inbox'/'$userName'/tmp'
    chgrp www-data $inbox/$userName
    chmod 775 $inbox/$userName
    chown www-data $inbox/$userName'/tmp'
    chgrp www-data $inbox/$userName'/tmp'
    chmod 775 $inbox/$userName'/tmp'
    chown www-data $inbox/$userName'/tmp'   
fi  

#ncftpget -u $USER -p $PASSWORD -DD $FTPHost $inbox'/'$userName $FTPPath'/'$userName/inbox/* 
cd $inbox/$userName'/tmp'
echo $FTPPath'/'$userName'/'inbox
ftp -4 -invp $FTPHost <<EOF
user $USER $PASSWORD
cd $FTPPath/$userName/inbox
mget *.*
mdel *.*
bye
EOF
mv $inbox/$userName'/tmp/'* $inbox/$userName/ 2>/dev/null



